// Resume Writer — LaTeX → PDF via latexonline.cc free compilation API.
// Falls back to pdf-lib if the compile service is unreachable.
// No new dependencies needed: uses Node's built-in https module.
// ponytail: ceiling = Overleaf API (private, no public endpoint). Upgrade path: self-host tectonic.

import * as fs from 'fs';
import * as https from 'https';
import * as http from 'http';
import * as path from 'path';

export interface ResumeData {
  name: string;
  email: string;
  phone: string;
  linkedIn: string;
  website: string;
  resumeContent: string;  // plain text from LLM, will be embedded in LaTeX body
}

// ─── LaTeX Template ───────────────────────────────────────────────────────────

function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g,  '\\&')
    .replace(/%/g,  '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g,  '\\#')
    .replace(/_/g,  '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g,  '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

/** Convert plain-text resume content into LaTeX body paragraphs. */
function contentToLatex(content: string): string {
  const lines = content.split('\n');
  const result: string[] = [];
  let inItemize = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      if (inItemize) {
        result.push('\\end{itemize}');
        inItemize = false;
      }
      continue;
    }

    if (/^[-•*]\s+/.test(trimmed)) {
      if (!inItemize) {
        result.push('\\begin{itemize}');
        inItemize = true;
      }
      result.push(`  \\item ${escapeLatex(trimmed.replace(/^[-•*]\s+/, ''))}`);
    } else {
      if (inItemize) {
        result.push('\\end{itemize}');
        inItemize = false;
      }

      if (/^[A-Z][A-Z\s]{3,}$/.test(trimmed) || /^[A-Z][^a-z]+:$/.test(trimmed)) {
        result.push(`\\section*{${escapeLatex(trimmed.replace(/:$/, ''))}}`);
      } else {
        result.push(escapeLatex(trimmed) + ' \\\\[2pt]');
      }
    }
  }

  if (inItemize) {
    result.push('\\end{itemize}');
  }

  return result.join('\n');
}

function buildLatex(data: ResumeData): string {
  const name      = escapeLatex(data.name || 'Candidate');
  const email     = escapeLatex(data.email || '');
  const phone     = escapeLatex(data.phone || '');
  const linkedin  = escapeLatex(data.linkedIn || '');
  const website   = escapeLatex(data.website || '');

  const contactParts = [email, phone, linkedin, website].filter(Boolean).join(' \\textbar{} ');
  const body = contentToLatex(data.resumeContent || 'No resume content provided.');

  return `\\documentclass[11pt,a4paper]{article}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage[margin=1.8cm]{geometry}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage{parskip}
\\usepackage{hyperref}
\\usepackage{xcolor}

% Typography
\\titleformat{\\section}{\\large\\bfseries\\color{black!80}}{}{0em}{}[\\titlerule]
\\setlist[itemize]{noitemsep, topsep=2pt, leftmargin=*}
\\pagestyle{empty}

\\begin{document}

% ─── Header ──────────────────────────────────────────────────────────────────
\\begin{center}
  {\\LARGE\\bfseries ${name}} \\\\[4pt]
  {\\small ${contactParts}}
\\end{center}

\\vspace{6pt}
\\hrule
\\vspace{8pt}

% ─── Body ────────────────────────────────────────────────────────────────────
${body}

\\vspace{12pt}
\\hrule
\\vspace{4pt}
{\\tiny \\textit{Generated by Career Copilot — tailored for this role}}

\\end{document}
`;
}

// ─── LaTeX Online Compilation ─────────────────────────────────────────────────

/**
 * POST LaTeX source to latexonline.cc and get PDF bytes back.
 * Uses Node built-in https — no npm dep needed.
 */
function compileLatexOnline(latexSource: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const boundary = `boundary${Date.now()}`;
    const filename  = 'resume.tex';
    const fileData  = Buffer.from(latexSource, 'utf8');

    const body = Buffer.concat([
      Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${filename}"\r\nContent-Type: text/plain\r\n\r\n`),
      fileData,
      Buffer.from(`\r\n--${boundary}--\r\n`),
    ]);

    const options: https.RequestOptions = {
      hostname: 'latexonline.cc',
      path:     '/compile',
      method:   'POST',
      headers: {
        'Content-Type':   `multipart/form-data; boundary=${boundary}`,
        'Content-Length': body.length,
      },
      timeout: 30_000,
    };

    const req = https.request(options, (res) => {
      // Follow redirect (latexonline.cc returns 302 to the PDF)
      if ((res.statusCode === 301 || res.statusCode === 302) && res.headers.location) {
        const loc = res.headers.location;
        const getter = loc.startsWith('https') ? https : http;
        getter.get(loc, { timeout: 30_000 }, (res2) => {
          const chunks: Buffer[] = [];
          res2.on('data', (c: Buffer) => chunks.push(c));
          res2.on('end',  () => resolve(Buffer.concat(chunks)));
          res2.on('error', reject);
        }).on('error', reject);
        return;
      }

      if (res.statusCode !== 200) {
        reject(new Error(`latexonline.cc returned HTTP ${res.statusCode}`));
        return;
      }

      const chunks: Buffer[] = [];
      res.on('data', (c: Buffer) => chunks.push(c));
      res.on('end',  () => {
        const buf = Buffer.concat(chunks);
        // Verify it's actually a PDF (starts with %PDF)
        if (buf.slice(0, 4).toString() !== '%PDF') {
          reject(new Error('latexonline.cc response is not a PDF'));
        } else {
          resolve(buf);
        }
      });
      res.on('error', reject);
    });

    req.on('timeout', () => { req.destroy(); reject(new Error('latexonline.cc timed out')); });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

// ─── Fallback: pdf-lib minimal PDF ───────────────────────────────────────────

async function fallbackPdf(data: ResumeData, outputPath: string): Promise<void> {
  // Dynamic import so pdf-lib is only loaded when needed
  const { PDFDocument, StandardFonts, rgb, PageSizes } = await import('pdf-lib');

  const doc     = await PDFDocument.create();
  const boldF   = await doc.embedFont(StandardFonts.HelveticaBold);
  const regF    = await doc.embedFont(StandardFonts.Helvetica);
  const page    = doc.addPage(PageSizes.A4);
  const [W, H]  = PageSizes.A4;
  const M       = 50;
  let y         = H - M;

  page.drawText(data.name || 'Candidate', { x: M, y, font: boldF, size: 18, color: rgb(0.1, 0.1, 0.3) });
  y -= 22;

  const contact = [data.email, data.phone, data.linkedIn, data.website].filter(Boolean).join('  |  ');
  if (contact) {
    page.drawText(contact, { x: M, y, font: regF, size: 10, color: rgb(0.4, 0.4, 0.4) });
    y -= 16;
  }

  y -= 8;
  page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) });
  y -= 14;

  const lines = (data.resumeContent || '').split('\n');
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) { y -= 10; continue; }
    if (y < M + 20) break;
    page.drawText(line.length > 95 ? line.substring(0, 95) + '…' : line, {
      x: M, y, font: regF, size: 10, color: rgb(0.1, 0.1, 0.1),
    });
    y -= 14;
  }

  fs.writeFileSync(outputPath, await doc.save());
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate a professional PDF from resume data.
 * Attempts LaTeX → latexonline.cc compilation first; falls back to pdf-lib.
 * Returns the output path.
 */
export async function generateResumePdf(
  data: ResumeData,
  outputPath: string,
  log?: (msg: string) => void,
): Promise<string> {
  const info = (msg: string) => log ? log(msg) : console.log(msg);

  // ── Primary: LaTeX → latexonline.cc ────────────────────────────────────
  try {
    info('[resume-writer] Building LaTeX source…');
    const latex = buildLatex(data);

    // Save .tex for debugging
    const texPath = outputPath.replace(/\.pdf$/, '.tex');
    fs.writeFileSync(texPath, latex, 'utf8');
    info(`[resume-writer] LaTeX written to ${path.basename(texPath)}`);

    info('[resume-writer] Compiling via latexonline.cc…');
    const pdfBytes = await compileLatexOnline(latex);
    fs.writeFileSync(outputPath, pdfBytes);
    info(`[resume-writer] ✅ PDF compiled (${pdfBytes.length} bytes) → ${path.basename(outputPath)}`);

    // Clean up .tex
    try { fs.unlinkSync(texPath); } catch { /* ignore */ }
    return outputPath;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    info(`[resume-writer] LaTeX compile failed (${msg}) — using fallback pdf-lib`);
  }

  // ── Fallback: pdf-lib ───────────────────────────────────────────────────
  await fallbackPdf(data, outputPath);
  info(`[resume-writer] Fallback PDF written → ${path.basename(outputPath)}`);
  return outputPath;
}
